### ISSUE TITLE
Sub meshes

### ISSUE THREAD

**Issue by Nolat** [BayatGames/VoxelFramework#1]
Hi !

What's sub meshes means ?
And is that possible to have complexe block like this image (like from MagicaVoxel) ?
https://images.gutefrage.net/media/fragen/bilder/strom-fuer-minechem/2_big.jpg?v=1453486472000](url)

**Comment by hasanbayatme** [comment]
Hi.
I would point to Unity official documentation:

- [Mesh.subMeshCount](https://docs.unity3d.com/ScriptReference/Mesh-subMeshCount.html)
- [Unity Answers: What is a submesh?](https://answers.unity.com/questions/684995/what-is-a-submesh.html)

Currently, it is not possible to import custom meshes, so that model or any similar models can't be imported, but you can implement Block Definition and make your own definition and include custom model support easily.
Thanks.
